In [4]:
import numpy as np

# 1D

In [5]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


In [16]:
arr.shape

(5,)

In [14]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[-1])

5


In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[1:5]

array([2, 3, 4, 5])

In [22]:
arr[3:]

array([4, 5, 6, 7])

In [21]:
arr[:5]

array([1, 2, 3, 4, 5])

In [23]:
arr[-5:-1]

array([3, 4, 5, 6])

# 2D 

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
arr.shape

(2, 5)

In [28]:
print(arr[1, 1:4])

[7 8 9]


In [29]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [30]:
print(arr[0:2, 2])

[3 8]


# ndarray.copy()

In [31]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


# np.min() & np.max()

In [33]:
arr = np.array([1, 5, 4, 8, 3, 7])
max_element = np.max(arr)
min_element = np.min(arr)
print("Max element:", max_element)
print("Min element:", min_element)

Max element: 8
Min element: 1


# ejercicio 1

In [39]:
def pregunta_1(matriz: list[list[int]]) -> tuple[list[int], list[int]]:
   mat = np.array(matriz)
   max_row = np.max(mat, axis=1)
   max_col = np.max(mat, axis=0)
   return max_row.tolist(), max_col.tolist()

# ejemplo
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
max_row, max_col = pregunta_1(matriz)
print("Max por fila:", max_row)
print("Max por columna:", max_col)

Max por fila: [3, 6, 9]
Max por columna: [7, 8, 9]


In [44]:
def pregunta_2(matriz: list[list[int]]) -> list[list[int]]:
    mat = np.array(matriz)
    n = len(mat[0])
    matriz_temporal = np.zeros((n, n), dtype=int)
    for i in range(n):
        for j in range(n):
            matriz_temporal[j][n-1-i] = mat[i][j]
    return matriz_temporal.tolist()

# ejemplo
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz_temporal = pregunta_2(matriz)
print("Matriz original:")
print(matriz)
print("Matriz rotado:")
print(matriz_temporal)

Matriz original:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Matriz rotado:
[[7, 4, 1], [8, 5, 2], [9, 6, 3]]


In [ ]:
t = ("a", "b", "c")  # Esto es una tupla
a = np.array(t)
a.tolist()

['a', 'b', 'c']

In [ ]:
def pregunta_4(lista1: list[int], lista2: list[int]) -> list[int]:
    result = []
    n = len(lista1)
    for i in range(n):
        result.append(lista1[i])
        result.append(lista2[i])
    return result

# ejemplo
lista1 = [1, 2, 3]
lista2 = [4, 5, 6]
resultado = pregunta_4(lista1, lista2)
print("Resultado de la intercalación:", resultado)

Resultado de la intercalación: [1, 4, 2, 5, 3, 6]


[1 2 3]
[4 5 6]

===
[1 4 2 5 3 6]

In [ ]:
str = "H"
a = str.islower()  # Esto es un método de cadena, no una función
a

True

In [ ]:
# len(str) < 8
# re.search(r'[a-z]', str)
# re.search(r'[A-Z]', str)
# re.search(r'\d', texto)
# pattern = r'\s'

In [ ]:
texto = "12341254HOLAMUNDO"

In [65]:
import re
texto = "Hola Mundo 123"
re.search(r'\d', texto)

<re.Match object; span=(11, 12), match='1'>

In [ ]:
import re
texto = "hola mundo 123"
# ¿Hay al menos una mayúscula?
if re.search(r'[a-z]', texto.upper()):
    print(f"'{texto}' contiene al menos una mayúscula.")
# ¿Hay al menos un número?
if re.search(r'\d', texto):
    print(f"'{texto}' contiene al menos un número.")
# ¿Contiene espacios?
if re.search(r'\s', texto):
    print(f"'{texto}' contiene espacios.")

'hola mundo 123' contiene al menos un número.
'hola mundo 123' contiene espacios.


In [55]:
a = (re.search(r'[a-z]', texto))

In [ ]:
vector = np.array([10, 20, 30, 40, 50])
print("Vector:", vector)
print("Primer elemento:", vector[0])      # 10
print("Tercer elemento:", vector[2])      # 30
print("-" * 30)

matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Matriz:")
print(matriz)
print("Elemento en fila 0, columna 1:", matriz[0, 1]) # 2
print("Elemento en fila 2, columna 0:", matriz[2, 0]) # 7